### ISSUE TITLE
Styles are broken in Firefox

### ISSUE THREAD

**Issue by kyleshevlin** [shipshapecode/ember-3d-nav#13]
Specifically, the nav items are not positioned correctly, probably due to vendor issues with various transforms. Will just take some refactoring.

![image](https://cloud.githubusercontent.com/assets/4333144/16969104/8d86362c-4dc7-11e6-86c6-9458d20a2dae.png)

**Comment by RobbieTheWagner** [comment]
@kyleshevlin weird, I was attempting to use autoprefixer to fix issues like this. Perhaps I did that incorrectly

**Comment by kyleshevlin** [comment]
Maybe, maybe not. I can look into it.

**Comment by RobbieTheWagner** [comment]
Fixed by #16
