### ISSUE TITLE
Error when inserting the links array

### ISSUE THREAD

**Issue by guilleBFG** [shipshapecode/ember-3d-nav#58]
Hi,
I wanted to thank you for this amazing add-on.
I followed the steps described on ember addons,
installed all the dependencies described, used the dummy in test to generate something similar to the example, but i couldnt manage to make it work (ember trows an error when creating the route aplicación and inserting the links array) when i start the app with ember serve ember trows an error no helper with command 'eq'.

I'm using the last version of ember-cli 2.9 , I wolud be greatfull if you could give me any feedback on how to correctly this add-on.

regards,
guilleBFG

**Comment by RobbieTheWagner** [comment]
Hi @guilleBFG, thanks for reporting this. This was because I forgot to move ember-truth-helpers to dependencies. I just published version 1.2.4 which should fix this issue. Give it a try!
